version: "3.8"

services:
  db-mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=todolist
      - MYSQL_USER=user
      - MYSQL_PASSWORD=usertodolist
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db-data:/mysql-data
    networks:
      - todolist-network
  app:
    depends_on:
      - db-mysql
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /usr/src/todolist
    container_name: todolist-api
    restart: on-failure
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/todolist
      - SPRING_DATASOURCE_USER=user
      - SPRING_DATASOURCE_PASSWORD=usertodolist
      - SPRING_DATASOURCE_DRIVER=com.mysql.cj.jdbc.Driver
    networks:
      - todolist-network

networks:
  todolist-network:

volumes:
  db-data: