spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:todolocal}
    username: ${SPRING_DATASOURCE_USER:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:} 
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    path: /api-docs